project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "src/main/resources/assets/dragonsurvival/lang/"
base_url: "https://dragonsurvivalteam.crowdin.com"

commit_message: "docs(lang): New translations %original_file_name% from Crowdin"
append_commit_message: false

files:
  - source: "en_us.json"
    translation: "/%locale_with_underscore%.json"
    update_option: update_as_unapproved
    skip_untranslated_strings: true