files:
  - source: /src/main/resources/assets/dragonsurvival/lang/en_us.json
    ignore:
      - needfix*
    translation: /src/main/resources/assets/dragonsurvival/lang/%locale_with_underscore%.json
