modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache License 2.0"
issueTrackerURL = "https://github.com/DragonSurvivalTeam/DragonSurvival/issues"
logoFile = "dragonsurvival.png"

[[mods]]
    modId = "dragonsurvival"
    version = "${file.jarVersion}"
    displayName = "Dragon Survival"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/dragons-survival"
    credits = "Arcaryx, NoCube, AIS, Jack Raiden, Maleus"
    authors = "Black Aures, Horeak, Alexiy"
    description = '''
        This mod lets you play as a dragon. There are 3 dragon kinds, which have different traits.
        To start, you must create a Dragon Altar where you can choose the dragon type you want to become.
        '''

[[dependencies.dragonsurvival]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3.0.47,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.dragonsurvival]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.67,)"