name: 1.19.2 Bug Report
description: File a bug report
title: "[1.19.2 Forge Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Make sure that you have removed the old configs and read the DS installation rules

  - type: input
    id: contact
    attributes:
      label: ■ Your Discord ID or other contacts
      description: How can we get in touch with you if we need more info?
      placeholder: BlackAures#7759
    validations:
      required: false

  - type: textarea
    id: version
    attributes:
      label: ■ Dragon Survival version and Modpack version (if have)
      description: Copy the full name of the file.
      placeholder: Example - DragonSurvival-1.19.2-1.5.43 + Become Dragon 1.19
    validations:
      required: true

  - type: dropdown
    id: server
    attributes:
      label: ■ Single game or server?
      description: There are huge differences between the dedicated server, local server and client. Be sure to correctly specify which version you are playing on.
      options:
        - Single (Default)
        - Dedicated Server or Host Sites
        - Local network (LAN, Hamachi, etc.)
    validations:
      required: true

  - type: dropdown
    id: configs
    attributes:
      label: ■ Do you delete old configs before writing a bug report?
      description: Removing old configs after major updates is essential for clean operation of many modifications. Also on the wiki there are instructions on how to solve most of the bugs and problems with our mod.
      options:
        - Nope (Default)
        - I always delete configs
        - Usually yes, but this time no.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: ■ Bug Description and Reproduce
      description: Please describe how we can get the same result as yours.
      placeholder: Description - I have been lying on the treasure for five minutes now, but nothing happens. 1. Put the treasure on the ground 2. Right-click on them 3. Just wait and nothing happens.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ■ Expected behavior
      description:  A clear and concise description of what you expected to happen.
      placeholder: I use treasures and expect them to give healing.
    validations:
      required: true

  - type: textarea
    id: crash-report
    attributes:
      label: ■ Crash Report File and Logs
      description: If your game or server crashes, game creates a file in crash-reports and log folder. Just grab that latest files and drag it into this box. No need to copy all text inside.
    validations:
      required: false
