name: Compatibility Report
description: Crashes the game in your modpack? Write about it here.
title: "[Compatibility]: "
labels: ["compatibility", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please only crash reports, not suggestions like "Don't let the dragons of mod X be friends with dragons from Dragon Survival"!
        
  - type: input
    id: contact
    attributes:
      label: ■ Your Discord ID or other contacts
      description: How can we get in touch with you if we need more info?
      placeholder: BlackAures#7759
    validations:
      required: false
      
  - type: textarea
    id: version
    attributes:
      label: ■ Dragon Survival version
      description: Copy the full name of the file.
      placeholder: Example - DragonSurvival_TreasureUpdate-1.16.5-0.9.2
    validations:
      required: true
      
  - type: dropdown
    id: version-mc
    attributes:
      label: ■ Minecraft version
      description: 1.16.5 or...?
      options:
        - 1.18.2 (Default)
        - 1.15
        - 1.16.5
        - 1.19.2
    validations:
      required: true  
      
  - type: dropdown
    id: server
    attributes:
      label: ■ Single game or server?
      description: There are huge differences between the dedicated server, local server and client. Be sure to correctly specify which version you are playing on.
      options:
        - Single (Default)
        - Dedicated Server or Host Sites
        - Local network (LAN, Hamachi, etc.)
    validations:
      required: true

  - type: dropdown
    id: configs
    attributes:
      label: ■ Do you delete old configs before writing a bug report?
      description: Removing old configs after major updates is essential for clean operation of many modifications. Also on the wiki there are instructions on how to solve most of the bugs and problems with our mod.
      options:
        - Nope (Default)
        - I always delete configs
        - Usually yes, but this time no.
    validations:
      required: true

  - type: textarea
    id: incompatibility
    attributes:
      label: ■ Description of incompatibility
      description: A clear and concise description of what the incompatibility is. If applicable, add screenshots to help explain your problem. Please only crash reports, not suggestions.
      placeholder: I remove Dragon Survival or mod X and the game starts working, but together this causes the game crashes.
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: ■ To Reproduce
      description: Is this error repeatable? If so, please describe how we can get the same result as yours.
      placeholder: 1. Install Dragon Survival and mod X 2. Try to open the game or interact with the item from X mod 3. Crash
    validations:
      required: true
      
       
  - type: textarea
    id: crash-report
    attributes:
      label: ■ Crash Report File and Logs
      description: If your game or server crashes, game creates a file in crash-reports and log folder. Just grab that latest files and drag it into this box. No need to copy all text inside.
    validations:
      required: false
