name: CI Semantic Releaser

on:
  push:
    branches: [ v1.16.x ]
  pull_request:
    branches: [ v1.16.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Releaser
        uses: brpaz/action-semantic-release@v1
        with:
            branch: v1.16.x
