name: CI Semantic Releaser

on:
  workflow_dispatch:
  push:
    branches: [ v1.16.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: "semantic-release @semantic-release/exec conventional-changelog-conventionalcommits"
          branches: "v1.16.x"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        if: steps.semantic.outputs.new_release_published == 'true'
        run: chmod +x gradlew

      - name: Setup forge mdk
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew init

      - name: Build with Gradle
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew build

      - name: Changelog
        shell: bash
        id: release_description
        run: |
            description= ${{ steps.semantic.outputs.new_release_version }}
            description="${description//'%'/'%25'}"
            description="${description//$'\n'/'%0A'}"
            description="${description//$'\r'/'%0D'}"
            echo "::set-output name=description::$description"

      - name: Send Discord alert
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "New experimental version released!"
          embed: |
            {
            "title": "Version ${{ steps.semantic.outputs.new_release_version }}",
            "description": "Changes:```\n${{ steps.release_description.outputs.description }}\n```",
            "footer":
              {
                "text": "⚠ This is an automatically generated file with untested content. Be extremely careful not to use this in your main world without creating backups⚠"
              }
            }

      - name: Discord early access publish
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: build/libs/*.jar