name: Crowdin Download

on:
  workflow_dispatch:
  schedule:
    # runs every day at 12:00 noon UTC
    - cron: '0 12 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

jobs:
  i18n-download-docs-translations:
    name: Language
    runs-on: ubuntu-latest

    steps:
      - name: Fetch the newest translations
        uses: crowdin/github-action@master
        with:
          config: "./crowdin.yml"
          upload_sources: true
          upload_translations: true
          download_translations: true
          skip_untranslated_strings: true
          skip_untranslated_files: true
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          upload_language: "us"