name: Crowdin Download

on:
  workflow_dispatch:
  schedule:
    # runs every day at 12:00 noon UTC
    - cron: '0 12 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

jobs:
  build:
    name: Language
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install crowdin
        run: npm i -g @crowdin/cli

      - name: Upload translations
        run: crowdin upload

      - name: Download translations
        run: crowdin download

      - name: Upload langs
        uses: EndBug/add-and-commit@v9
        with:
          add: "src/main/resources/assets/dragonsurvival/lang/*"
          message: "docs(lang): Updating Crowdin translations"